route:
  receiver: local-webhook
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h

receivers:
  - name: local-webhook
    webhook_configs:
      - url: 'http://alert-receiver:5001/alerts'
        send_resolved: true
